E_Shop.Web/Areas/Admin/Controllers/IVAController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web.Mvc;
using E_Shop.CORE.Contracts;
using E_Shop.CORE.Domain.Classes;
using E_Shop.Web.Areas.Admin.Models.IVA;
using E_Shop.Web.JQueryDataTable;
using RestSharp;

namespace E_Shop.Web.Areas.Admin.Controllers
{
    /// <summary>
    /// Controlador de los IVAs - Solo accesible con el rol Admin
    /// </summary>
    [Authorize(Roles = "Admin")]
    public class IVAController : Controller
    {
        private IIVAManager ivaManager;

        /// <summary>
        /// Constructor del controlador
        /// </summary>
        /// <param name="ivaManager"></param>
        public IVAController(IIVAManager ivaManager)
        {
            this.ivaManager = ivaManager;
        }

        /// <summary>
        /// Método que devuelve todos los IVAs en formato JSon para pintar una tabla con Ajax
        /// </summary>
        /// <returns></returns>
        public ActionResult IndexData()
        {
            JQueryDataTableRequest request = new JQueryDataTableRequest(System.Web.HttpContext.Current.Request);
            var model =
                ivaManager.GetAll()
                    .Select(e => new IVAIndexViewModel()
                    {
                        Id = e.Id,
                        Name = e.Name,
                        Value = e.Value
                    });

            JQueryDataTableResponse result = JQueryHelper.CreateJQueryDataTableResponse(model, request);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Método que muestra una tabla con todos los IVAs
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var model =
               ivaManager.GetAll()
                   .Select(e => new IVAIndexViewModel()
                   {
                       Id = e.Id,
                       Name = e.Name,
                       Value = e.Value
                   });

            return View(model);
        }

        /// <summary>
        /// Método que pinta la vista de creación de un IVA
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            IVACreateViewModel model = new IVACreateViewModel();

            return View(model);
        }

        /// <summary>
        /// Método que crea un IVA
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(IVACreateViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ivaManager.Add(model.IVA);
                    ivaManager.db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch (DbEntityValidationException e)
            {
                return View("Error" + e);
            }
        }

        /// <summary>
        /// Método que pinta la vista de edición de un IVA
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            IVACreateViewModel model = new IVACreateViewModel();
            model.IVA = ivaManager.GetById(id);

            return View(model);
        }

        /// <summary>
        /// Método de edición de un IVA
        /// </summary>
        /// <param name="id"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(int id, IVACreateViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ivaManager.Edit(id, model.IVA);
                    ivaManager.db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                return View(model);
            }
        }

        /// <summary>
        /// Método que devuelve los resultados del web service
        /// </summary>
        /// <returns></returns>
        public ActionResult TestService()
        {
            var client = new RestClient("http://localhost:65371/");
            var request = new RestRequest("api/IVA", Method.GET) { RequestFormat = DataFormat.Json };
            var response = client.Execute<List<IVA>>(request);

            if (response.Data == null)
            {
                throw new Exception(response.ErrorMessage);
            }
            return View(response.Data);
        }
    }
}

E_Shop.Web/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using E_Shop.CORE.Contracts;
using E_Shop.CORE.Domain.Classes;
using E_Shop.Web.Models.Shop;

namespace E_Shop.Web.Controllers
{
    
    /// <summary>
    /// Controlador de la parte de muestra de variedades de la tienda
    /// </summary>
    public class ShopController : Controller
    {
        private IFamilyManager familyManager;
        private IVarietyManager varietyManager;
        private ICommentManager commentManager;

        /// <summary>
        /// Constructor del controlador
        /// </summary>
        /// <param name="familyManager"></param>
        /// <param name="varietyManager"></param>
        /// <param name="commentManager"></param>
        public ShopController(IFamilyManager familyManager, IVarietyManager varietyManager, ICommentManager commentManager)
        {
            this.familyManager = familyManager;
            this.varietyManager = varietyManager;
            this.commentManager = commentManager;
        }

       

        /// <summary>
        /// Método para mostrar un listado de variedades (las 12 primeras)
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var model = varietyManager.GetAll()
                    .Select(p => new ListViewModel()
                    {
                        Id = p.Id,
                        Name = p.Product.Brand + " - " + p.Product.Model,
                        Brand = p.Product.Brand,
                        Price = p.Product.Price
                    }).ToList();

            return View(model);
        }

        /// <summary>
        /// Método para filtrar las variedades por familia
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ListByFamily(int id)  
        {
            var model = varietyManager.GetAllByProductFamily(id)
                    .Select(p => new ListViewModel()
                    {
                        Id = p.Id,
                        Name = p.Product.Brand + " - " + p.Product.Model,
                        Price = p.Product.Price,
                    }).ToList();

            return PartialView("_ListPartial", model);
        }

        /// <summary>
        /// Método de llena las propiedades de la clase FamilyViewModel, deuna manera recursiva
        /// </summary>
        /// <param name="families"></param>
        /// <param name="parentId"></param>
        /// <returns></returns>
        private List<FamilyMenuViewModel> GetElements(List<Family> families, int? parentId = null)
        {
            List<FamilyMenuViewModel> result = new List<FamilyMenuViewModel>();
            foreach (var family in families.Where(f => f.ParentId == parentId))
            {
                result.Add(new FamilyMenuViewModel()
                {
                    ParentFamily = family,
                    SonFamily = GetElements(families, family.Id)
                });
            }
            return result;
        }

        /// <summary>
        /// Método que pinta todas las familias y subfamilias de una variedad en una vista parcial para fitrar por ellas
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult FamilyMenu()
        {
            var families = familyManager.GetAll().ToList();
            FamilyMenuViewModel model = GetElements(families).FirstOrDefault();

            return PartialView("_FamilyMenu", model);
        }

        /// <summary>
        /// Método para filtrar las variedades por marca
        /// </summary>
        /// <param name="brand"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ListByBrand(string brand)
        {
            var model = varietyManager.GetAllByProductBrand(brand)
                    .Select(p => new ListViewModel()
                    {
                        Id = p.Id,
                        Name = p.Product.Brand + " - " + p.Product.Model,
                        Price = p.Product.Price
                    }).ToList();

            return PartialView("_ListPartial", model);
        }

        /// <summary>
        /// Método para filtrar las variedades por precio
        /// </summary>
        /// <param name="price1"></param>
        /// <param name="price2"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ListByPrice(decimal price1, decimal price2)
        {
            var model = varietyManager.GetAllByProductPriceRange(price1, price2)
                    .Select(p => new ListViewModel()
                    {
                        Id = p.Id,
                        Name = p.Product.Brand + " - " + p.Product.Model,
                        Price = p.Product.Price,
                    }).ToList();

            return PartialView("_ListPartial", model);
        }

        /// <summary>
        /// Método que muestra los detalles de una variedad
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int id)
        {
            var variety = varietyManager.GetById(id);
            var comments = commentManager.GetAllByVarietyId(id).ToList();
            var referenceUri = new Uri(@Server.MapPath("~\\Images\\Product\\"));
            var imageFiles = Directory.GetFiles(@Server.MapPath("~\\Images\\Product\\"), id + "_*")
                .Select(file => new Uri(file)).Select(fileUri => "/Images/Product/" + referenceUri.MakeRelativeUri(fileUri).ToString()).ToList();

            var quantity = new List<SelectListItem>();
            for (var i = 1; i < variety.Stock + 1; i++)
                quantity.Add(new SelectListItem { Text = i.ToString(), Value = i.ToString() });

            ViewBag.list = quantity;

            DetailsViewModel model = new DetailsViewModel()
                                         {
                                             Id = id,
                                             Name = variety.Product.FullName,
                                             Price = variety.Product.Price.ToString("n2"),
                                             Weight = variety.Weight.ToString("n2"),
                                             Variety = variety,
                                             ImagesFiles = imageFiles,
                                             Image = imageFiles.FirstOrDefault(),
                                             Comments = comments,
                                             Stock = variety.Stock,
                                             Quantity = quantity
            };

            return View(model);
        }
        

        /// <summary>
        /// Método que pinta la pantalla de creción de un comentario de una variedad
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize]
        public ActionResult CreateComment(int id)
        {
            DetailsViewModel model = new DetailsViewModel();
            model.Id = id;

            return View(model);
        }

        /// <summary>
        /// Método de creación de un comentario de una variedad
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateComment(DetailsViewModel model, int id)
        {
            model.User = User.Identity.Name;
            model.Date = DateTime.Now;
            model.Id = id;

            try
            {
                if (ModelState.IsValid)
                {
                     var comment = new Comment()
                                          {
                                              Id = new int(),
                                              User = model.User,
                                              DateTime = model.Date,
                                              VarietyId = model.Id,
                                              Text = model.Text
                                          };

                    commentManager.Add(comment);
                    commentManager.db.SaveChanges();
                    return RedirectToAction("Details", new { id = model.Id });
                }
                return View(model);
            }
            catch (Exception e)
            {
                return View("Error" + e);
            }
        }
    }
}

E_Shop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EShop - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/template")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<header id="header">
    <div class="header_top">
        <div class="container">
            <div class="col-sm-6">
                <div class="contactinfo ">
                    <ul class="nav nav-pills ">
                        <li>
                            <a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-envelope"></i> info@eshop.com</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="social-icons pull-right">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="https://www.facebook.com/">
                                <i class="fa fa-facebook"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://twitter.com/">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.linkedin.com/">
                                <i class="fa fa-linkedin"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://dribbble.com/">
                                <i class="fa fa-dribbble"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://plus.google.com/">
                                <i class="fa fa-google-plus"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div><!--/header_top-->
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("E Shop", "Index", "Shop", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @if (User.IsInRole("Admin"))
                        {
                            <a href="#">Admin<i class="fa fa-angle-down"></i></a>
                            <ul class="sub-menu">
                                <li>@Html.ActionLink("Productos", "Index", "Product", new { area = "Admin" }, new { @class = "" })</li>
                                <li>@Html.ActionLink("Variedades", "Index", "Variety", new { area = "Admin" }, new { @class = "" })</li>
                                <li>@Html.ActionLink("Familias", "Index", "Family", new { area = "Admin" }, new { @class = "" })</li>
                                <li>@Html.ActionLink("IVAs", "Index", "IVA", new { area = "Admin" }, new { @class = "" })</li>
                                <li>@Html.ActionLink("Comentarios", "Index", "Comment", new { area = "Admin" }, new { @class = "" })</li>
                                <li>@Html.ActionLink("Pedidos", "Index", "Order", new { area = "Admin" }, new { @class = "" })</li>
                            </ul>
                        }
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>


</header><!--/header-->

<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer id="footer">
        <!--Footer-->
        <div class="footer-widget">
            <div class="container">
                <div class="row">
                    <div class="col-sm-2 col-xs-">
                        <div class="single-widget">
                            <h2>Servicios</h2>
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="#">Ayuda Online</a></li>
                                <li><a href="#">Contacta con nosotros</a></li>
                                <li><a href="#">Estado del pedido</a></li>
                                <li><a href="#">Cambiar dirección</a></li>
                                <li><a href="#">FAQ’s</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="single-widget">
                            <h2>Nuestros productos</h2>
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="#">Guitarras</a></li>
                                <li><a href="#">Bajos</a></li>
                                <li><a href="#">Baterías</a></li>
                                <li><a href="#">Teclados</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="single-widget">
                            <h2>Políticas</h2>
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="#">Términos de uso</a></li>
                                <li><a href="#">Política de privacidad</a></li>
                                <li><a href="#">Pólitica de devoluciones</a></li>
                                <li><a href="#">Sistema de envío</a></li>
                                <li><a href="#">Sistema de tickets</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="single-widget">
                            <h2>Acerca de nosotros</h2>
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="#">Información de la compañía</a></li>
                                <li><a href="#">Trabaja con nosotros</a></li>
                                <li><a href="#">Dónde estamos</a></li>
                                <li><a href="#">Programa de afiliación</a></li>
                                <li><a href="#">Copyright</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="single-widget">
                            <h2>Mantente informado</h2>
                            <form action="#" class="searchform">
                                <input type="text" placeholder="Tu dirección de correo"/>
                                <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                                <p>Recibe información sobre nuestras últimas <br />novedades 
                                </p>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <p class="pull-left">Copyright © 2016 E-SHOP Inc. Todos los derechos reservados.</p>
                    <p class="pull-right">Diseñado por Daniel Ortiz Plaza</p>
                </div>
            </div>
        </div>

    </footer><!--/Footer-->
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/template")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/zoom")
@RenderSection("scripts", required: false)
</body>
</html>

E_Shop.Web/Views/Shared/_ListPartial.cshtml
@model IEnumerable<E_Shop.Web.Models.Shop.ListViewModel>

@foreach (var p in Model)
{
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <a href="@Url.Action("Details", "Shop", new { id = @p.Id })">
                        <div class="productinfo" style="height: 370px; width: 255px;">
                            <div id="imagenlistaproducto">
                                <img src="@p.Image" style="max-height: 250px; max-width: 250px; height: auto; width: auto; " />
                            </div>
                            <div id="pieimagen" style="height: 30px; width: 255px;">
                                <h3>@p.Name</h3>
                                <h2>@p.Price</h2>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
}

E_Shop.Web/Views/Shared/_Menu.cshtml
@model E_Shop.Web.Models.Shop.FamilyMenuViewModel

    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          @foreach (var f in Model.SonFamily)
          {
            <li>
                <a href="">@f.ParentFamily.Name<i class="fa fa-angle-down"></i></a>
                <ul class="sub-menu">
                    @foreach (var r in Model.SonFamily.Where(r => r.ParentFamily.Id == f.ParentFamily.Id))
                {
                    foreach (var t in r.SonFamily)
                    {
                            <li><a class="families" data-id="@t.ParentFamily.Id" href="">@t.ParentFamily.Name</a></li>
                        }
                    }
                </ul>
            </li>
            
          }
            <li>
                @if (User.IsInRole("Admin"))
                {
                    <a href="#">Admin<i class="fa fa-angle-down"></i></a>
                            <ul class="sub-menu">
                                <li>@Html.ActionLink("Productos", "Index", "Product", new { area = "Admin" }, new { @class = "" })</li>
                                <li>@Html.ActionLink("Variedades", "Index", "Variety", new { area = "Admin" }, new { @class = "" })</li>
                                <li>@Html.ActionLink("Familias", "Index", "Family", new { area = "Admin" }, new { @class = "" })</li>
                                <li>@Html.ActionLink("IVAs", "Index", "IVA", new { area = "Admin" }, new { @class = "" })</li>
                                <li>@Html.ActionLink("Comentarios", "Index", "Comment", new { area = "Admin" }, new { @class = "" })</li>
                                <li>@Html.ActionLink("Pedidos", "Index", "Order", new { area = "Admin" }, new { @class = "" })</li>
                            </ul>
                }
            </li>
        </ul>
        @Html.Partial("_LoginPartial")
    </div>

@section Scripts
{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {

            $(".families").click(function () {
                var id = $(this).data("id");
                $.ajax({
                    url: '@Url.Action("ListByFamily", "Shop")',
                    type: 'GET',
                    data: { id: id }
                }).done(function (response) {
                    @Url.Action("Index", "Shop")
                    $("#dvList").html(response);
                });
            });
        });
    </script>
}