E_Shop.Web/Models/Shop/DetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;

using E_Shop.CORE.Domain.Classes;

namespace E_Shop.Web.Models.Shop
{
    public class DetailsViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Price { get; set; }

        public string Weight { get; set; }

        public Variety Variety { get; set; }

        public string Image { get; set; }

        public List<string> ImagesFiles { get; set; }

        public List<Comment> Comments { get; set; }

        public string User { get; set; }

        public DateTime Date { get; set; }

        public Comment Comment { get; set; }

        public string Text { get; set; }

        public List<SelectListItem> Quantity{ get; set; }

        public int Stock { get; set; }
    }
}

E_Shop.Web/Models/Shop/FamilyMenuViewModel.cs
using System.Collections.Generic;
using System.Linq;

using E_Shop.CORE.Domain.Classes;

namespace E_Shop.Web.Models.Shop
{
    public class FamilyMenuViewModel
    {
        public Family ParentFamily { get; set; }
        public List<FamilyMenuViewModel> SonFamily { get; set; }
    }
}

E_Shop.Web/Models/Shop/ListViewModel.cs
using System.Collections.Generic;

using E_Shop.CORE.Domain.Classes;

namespace E_Shop.Web.Models.Shop
{
    public class ListViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Brand { get; set; }

        public decimal Price { get; set; }

        public string Image
        {
            get
            {
                return "/Images/Product/" + BuildNameImage(Id);
            }
            private set { }
        }

        private string BuildNameImage(int varietyId)
        {
            return $"{varietyId}_0.jpg";
        }
    }
}

E_Shop.Web/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using E_Shop.CORE.Contracts;
using E_Shop.CORE.Domain.Classes;
using E_Shop.Web.Models.Shop;

namespace E_Shop.Web.Controllers
{
    
    /// <summary>
    /// Controlador de la parte de muestra de variedades de la tienda
    /// </summary>
    public class ShopController : Controller
    {
        private IFamilyManager familyManager;
        private IVarietyManager varietyManager;
        private ICommentManager commentManager;

        /// <summary>
        /// Constructor del controlador
        /// </summary>
        /// <param name="familyManager"></param>
        /// <param name="varietyManager"></param>
        /// <param name="commentManager"></param>
        public ShopController(IFamilyManager familyManager, IVarietyManager varietyManager, ICommentManager commentManager)
        {
            this.familyManager = familyManager;
            this.varietyManager = varietyManager;
            this.commentManager = commentManager;
        }

       

        /// <summary>
        /// Método para mostrar un listado de variedades (las 12 primeras)
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var model = varietyManager.GetAll()
                    .Select(p => new ListViewModel()
                    {
                        Id = p.Id,
                        Name = p.Product.Brand + " - " + p.Product.Model,
                        Brand = p.Product.Brand,
                        Price = p.Product.Price
                    }).ToList();

            return View(model);
        }

        /// <summary>
        /// Método para filtrar las variedades por familia
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ListByFamily(int id)  
        {
            var model = varietyManager.GetAllByProductFamily(id)
                    .Select(p => new ListViewModel()
                    {
                        Id = p.Id,
                        Name = p.Product.Brand + " - " + p.Product.Model,
                        Price = p.Product.Price,
                    }).ToList();

            return PartialView("_ListPartial", model);
        }

        /// <summary>
        /// Método de llena las propiedades de la clase FamilyViewModel, deuna manera recursiva
        /// </summary>
        /// <param name="families"></param>
        /// <param name="parentId"></param>
        /// <returns></returns>
        private List<FamilyMenuViewModel> GetElements(List<Family> families, int? parentId = null)
        {
            List<FamilyMenuViewModel> result = new List<FamilyMenuViewModel>();
            foreach (var family in families.Where(f => f.ParentId == parentId))
            {
                result.Add(new FamilyMenuViewModel()
                {
                    ParentFamily = family,
                    SonFamily = GetElements(families, family.Id)
                });
            }
            return result;
        }

        /// <summary>
        /// Método que pinta todas las familias y subfamilias de una variedad en una vista parcial para fitrar por ellas
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult FamilyMenu()
        {
            var families = familyManager.GetAll().ToList();
            FamilyMenuViewModel model = GetElements(families).FirstOrDefault();

            return PartialView("_FamilyMenu", model);
        }

        /// <summary>
        /// Método para filtrar las variedades por marca
        /// </summary>
        /// <param name="brand"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ListByBrand(string brand)
        {
            var model = varietyManager.GetAllByProductBrand(brand)
                    .Select(p => new ListViewModel()
                    {
                        Id = p.Id,
                        Name = p.Product.Brand + " - " + p.Product.Model,
                        Price = p.Product.Price
                    }).ToList();

            return PartialView("_ListPartial", model);
        }

        /// <summary>
        /// Método para filtrar las variedades por precio
        /// </summary>
        /// <param name="price1"></param>
        /// <param name="price2"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ListByPrice(decimal price1, decimal price2)
        {
            var model = varietyManager.GetAllByProductPriceRange(price1, price2)
                    .Select(p => new ListViewModel()
                    {
                        Id = p.Id,
                        Name = p.Product.Brand + " - " + p.Product.Model,
                        Price = p.Product.Price,
                    }).ToList();

            return PartialView("_ListPartial", model);
        }

        /// <summary>
        /// Método que muestra los detalles de una variedad
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int id)
        {
            var variety = varietyManager.GetById(id);
            var comments = commentManager.GetAllByVarietyId(id).ToList();
            var referenceUri = new Uri(@Server.MapPath("~\\Images\\Product\\"));
            var imageFiles = Directory.GetFiles(@Server.MapPath("~\\Images\\Product\\"), id + "_*")
                .Select(file => new Uri(file)).Select(fileUri => "/Images/Product/" + referenceUri.MakeRelativeUri(fileUri).ToString()).ToList();

            var quantity = new List<SelectListItem>();
            for (var i = 1; i < variety.Stock + 1; i++)
                quantity.Add(new SelectListItem { Text = i.ToString(), Value = i.ToString() });

            ViewBag.list = quantity;

            DetailsViewModel model = new DetailsViewModel()
                                         {
                                             Id = id,
                                             Name = variety.Product.FullName,
                                             Price = variety.Product.Price.ToString("n2"),
                                             Weight = variety.Weight.ToString("n2"),
                                             Variety = variety,
                                             ImagesFiles = imageFiles,
                                             Image = imageFiles.FirstOrDefault(),
                                             Comments = comments,
                                             Stock = variety.Stock,
                                             Quantity = quantity
            };

            return View(model);
        }
        

        /// <summary>
        /// Método que pinta la pantalla de creción de un comentario de una variedad
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize]
        public ActionResult CreateComment(int id)
        {
            DetailsViewModel model = new DetailsViewModel();
            model.Id = id;

            return View(model);
        }

        /// <summary>
        /// Método de creación de un comentario de una variedad
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateComment(DetailsViewModel model, int id)
        {
            model.User = User.Identity.Name;
            model.Date = DateTime.Now;
            model.Id = id;

            try
            {
                if (ModelState.IsValid)
                {
                     var comment = new Comment()
                                          {
                                              Id = new int(),
                                              User = model.User,
                                              DateTime = model.Date,
                                              VarietyId = model.Id,
                                              Text = model.Text
                                          };

                    commentManager.Add(comment);
                    commentManager.db.SaveChanges();
                    return RedirectToAction("Details", new { id = model.Id });
                }
                return View(model);
            }
            catch (Exception e)
            {
                return View("Error" + e);
            }
        }
    }
}

E_Shop.Web/Controllers/ShoppingCartsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using E_Shop.Application;
using E_Shop.CORE.Contracts;
using E_Shop.CORE.Domain.Classes;
using E_Shop.Web.Models.ShoppingCart;

namespace E_Shop.Web.Controllers
{
    /// <summary>
    /// Controlador del proceso de llenado del carrito de la compra
    /// </summary>
    public class ShoppingCartsController : Controller
    {
        private IVarietyManager varietyManager;
        private IShoppingCartManager shoppingCartManager;

        /// <summary>
        /// Constructor del controlador
        /// </summary>
        /// <param name="varietyManager"></param>
        /// <param name="shoppingCartManager"></param>
        public ShoppingCartsController(IVarietyManager varietyManager, IShoppingCartManager shoppingCartManager)
        {
            this.varietyManager = varietyManager;
            this.shoppingCartManager = shoppingCartManager;
        }

        /// <summary>
        /// Método que muestra el carrito con todos los items por sesión
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var cart = Cart.GetCart(HttpContext);
            decimal total = cart.GetTotal();
            decimal iva = cart.GetIVA() * total;
            if (ModelState.IsValid)
            {
                var viewModel = new ShoppingCartViewModel
                                    {
                                        CartItems = cart.GetCartItems(),
                                        CartTotal = decimal.Round(total, 2, MidpointRounding.AwayFromZero),
                                        Subtotal = total - decimal.Round(iva, 2, MidpointRounding.AwayFromZero),
                                        IVA = decimal.Round(iva, 2, MidpointRounding.AwayFromZero)
                };
                return View(viewModel);
            }
            return View();
        }

        /// <summary>
        /// Método que añade una variedad / item al carrito
        /// </summary>
        /// <param name="id"></param>
        /// <param name="cantidad"></param>
        /// <returns></returns>
        public ActionResult AddToCart(int id, int cantidad)
        {
            var cart = Cart.GetCart(HttpContext);
            var variety = varietyManager.GetById(id);
            var cartItem =
                shoppingCartManager.GetAll()
                    .SingleOrDefault(c => c.CartId == cart.ShoppingCartId && c.Variety.Id == variety.Id);

            variety.Stock = variety.Stock - cantidad;
            varietyManager.Edit(id, variety);
            varietyManager.db.SaveChanges();

            if (cartItem == null)
            {
                cartItem = new ShoppingCart
                {
                    VarietyId = variety.Id,
                    CartId = cart.ShoppingCartId,
                    Count = cantidad,
                    DateCreated = DateTime.Now,
                };
                shoppingCartManager.Add(cartItem);
            }
            else
            {
                cartItem.Count++;
            }
            shoppingCartManager.db.SaveChanges();

            Session["varietyId"] = id;

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Método que elimina por llamada Ajax un item del carrito
        /// </summary>
        /// <param name="recordId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult RemoveFromCart(int recordId)
        {
            var cart = Cart.GetCart(HttpContext);
            var cartItem = shoppingCartManager.GetAll().Single(c => c.CartId == cart.ShoppingCartId && c.RecordId == recordId);
            var varietyId = (int)Session["varietyId"];
            var variety = varietyManager.GetById(varietyId);

            int itemCount = 0;

            if (cartItem != null)
            {                
                if (cartItem.Count > 1)
                {
                    cartItem.Count--;
                    itemCount = cartItem.Count;
                }
                else
                {
                    shoppingCartManager.Delete(cartItem); 
                }

                variety.Stock = variety.Stock + 1;
                varietyManager.Edit(varietyId, variety);
                varietyManager.db.SaveChanges();

                shoppingCartManager.db.SaveChanges();
            }

            var results = new ShoppingCartRemoveViewModel
                              {
                                  CartTotal = cart.GetTotal(),
                                  CartCount = cart.GetCount(),
                                  ItemCount = itemCount,
                                  DeleteId = recordId
            };
            return Json(results);
        }

        /// <summary>
        /// Método que muestra en el menú el número de elementos que contiene el carrito
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = Cart.GetCart(HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("_CartSummary");
        }
    }
}

E_Shop.Web/Views/Shop/CreateComment.cshtml
@model E_Shop.Web.Models.Shop.DetailsViewModel

<h2 class="col-md-12 col-md-offset-4">Nuevo comentario</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m=>m.Id);
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
           
            <div class="col-md-12 col-md-offset-4">
                @Html.TextAreaFor(model => model.Text,5,50,  new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-4 col-md-12">
            <input type="submit" value="Añadir" class="btn btn-fefault" />
        </div>
    </div>
}
<div>
    @Html.ActionLink("Volver al instrumento", "Details", new {id = Model.Id })
</div> 

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

E_Shop.Web/Views/Shop/Details.cshtml
@model E_Shop.Web.Models.Shop.DetailsViewModel
@{
    ViewBag.Title = "Details";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <section>
        <div class="container">
            <div class="row">
                <div class="col-sm-12 ">
                    <div class="product-details">
                        <!--product-details-->
                        <div id="gal1" class="col-sm-4 col-md-offset-1">
                            <div class="item" style="background-image: @Model.Image">
                                <img id="zoom_03" src="@Model.Image" data-zoom-image="@Model.Image" style="max-width: 400px; max-height: 300px;  height: auto; width:auto;" alt=""/>
                            </div>
                            <div id="similar-product" class="carousel-img">
                                <!-- Wrapper for slides -->
                                <div class="carousel-inner">
                                    <div class="img-box" style="height: auto; width: auto">
                                        @foreach (var image in Model.ImagesFiles)
                                        {
                                            <a href="#" data-image="@image" data-zoom-image="@image" style="width: 50px; height: 50px">
                                                <img id="im" src="@image" style="max-width: 50px; max-height: 50px; height: auto; width:auto;" alt="">
                                            </a>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="product-information">
                                <!--/product-information-->
                                <h3>@Html.DisplayFor(model => model.Name)</h3>
                                <p>
                                    <b>Unidades Disponibles: </b>@Html.DisplayFor(model => model.Stock, new { @id = "stock" })
                                </p>
                                <p>
                                    <b class="cantidad">Cantidad:</b>
                                    @Html.DropDownListFor(model => model.Quantity, new SelectList(ViewBag.list, "Text", "Value"))
                                </p>
                                <p>
                                    <span>
                                    <span>@Html.DisplayFor(model => model.Price)€</span>
                                </span>
                                </p>
                                <p>
                                    <b>Color:</b> @Html.DisplayFor(model => model.Variety.Colour)</p>
                                <p>
                                    <b>Material:</b> @Html.DisplayFor(model => model.Variety.Material)</p>
                                <p>
                                    <b>Peso:</b> @Html.DisplayFor(model => model.Weight) Kgs
                                </p>
                                
                                <span>
                                    <button type="button" class="btn btn-fefault cart">
                                        <i class="fa fa-shopping-cart"></i>
                                        @Html.ActionLink("Añadir al carrito", "AddToCart", "ShoppingCarts", new { id = Model.Id, cantidad = 'x'}, new { @id = "addToCart"})
                                    </button>
                            </span>
                                
                            </div><!--/product-information-->
                        </div>
                    </div><!--/product-details-->

                    <div class="category-tab shop-details-tab">
                        <!--category-tab-->
                        <h2 class="title text-center">Comentarios</h2>
                        <div class="tab-content">
                            <div class="tab-pane fade active in" id="reviews">
                                @foreach (var c in Model.Comments)
                                {
                                    <div class="col-sm-12">
                                        <ul>
                                            <li>
                                                <a href="">
                                                    <i class="fa fa-user"></i>@c.User</a>
                                            </li>
                                            <li>
                                                <a href="">
                                                    <i class="fa fa-clock-o"></i>@c.DateTime</a>
                                            </li>
                                        </ul>
                                        <p>@c.Text</p>
                                    </div>
                                }
                            </div>
                        </div>
                    </div><!--/category-tab-->
                    <button type="button" class="btn btn-fefault cart center">
                        <i class="fa fa-shopping-cart"></i>
                        @Html.ActionLink("Añadir Comentario", "CreateComment", "Shop", new { id = Model.Id }, "")
                    </button>
                </div>
            </div>
        </div>
    </section>
}

@section Scripts
{
    <script type="text/javascript">
        var $ = jQuery.noConflict();

        //Método que elige una imagen de una galería de imágenes
        $("#zoom_03").elevateZoom({ gallery: 'gal1', cursor: 'pointer', galleryActiveClass: 'active', imageCrossfade: true });
        $("#zoom_03").bind("click", function(e) {
            var ez = $('#zoom_03').data('elevateZoom');
            $.fancybox(ez.getGalleryList());
            return false;
        });

        //Método que encapsula la cantidad seleccionada para pasarsela al método "addToCart" del controlador del carrito
        $("#addToCart").click(function() {
            var cantidad = $("#Quantity").val();
            this.href = this.href.replace("x", cantidad);

            if (cantidad === null) {
                alert("En este momento no quedan unidades disponibles de este producto, en breves recibiremos más");
                return false;
            }
        });

        //Método que bloquea el link del carrito de la compra si está vacío
        $("#cart-status").click(function () {
            if ($('#cart-status').text() === 'Carrito (0)') {
                return false;
            }
        });
    </script>
}

E_Shop.Web/Views/Shop/GetProductVarieties.cshtml
@model IEnumerable<E_Shop.Web.Models.Shop.DetailsViewModel>

<div class="carousel-inner">
    @foreach (var image in Model)
    {
        <img id="" src="@image" style="width: 50px; height: 50px">
    }
</div>

E_Shop.Web/Views/Shop/_FamilyMenu.cshtml
@model E_Shop.Web.Models.Shop.FamilyMenuViewModel

<div class="panel-group category-products" id="accordian">
    <!--category-products-->
    <div class="panel panel-default">
        @foreach (var f in Model.SonFamily)
        {
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent=".accordian" href="#fam@(f.ParentFamily.Id)">
                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                        @f.ParentFamily.Name
                    </a>
                </h4>
            </div>
            <div id="fam@(f.ParentFamily.Id)" class="panel-collapse collapse">
                <div class="panel-body">
                    @foreach (var r in Model.SonFamily.Where(r => r.ParentFamily.Id == f.ParentFamily.Id))
                    {
                        foreach (var t in r.SonFamily)
                        {
                            <ul>
                                <li>
                                    <a class="families" data-id="@t.ParentFamily.Id" href="javascript:void(0);">@t.ParentFamily.Name</a>
                                </li>
                            </ul>
                        }
                    }
                </div>
            </div>
        }
    </div>
</div>